# Generated by Django 6.1.1 on 2026-10-06 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_attempts_to_users(apps, schema_editor):
    # Best-effort: attempts recorded under a username the account has since
    # changed away from cannot be matched and stay unlinked.
    LoginAttempt = apps.get_model('accounts', 'LoginAttempt')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    for user in User.objects.only('id', 'username').iterator():
        LoginAttempt.objects.filter(
            user__isnull=True,
            username__iexact=user.username,
        ).update(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_admin_impersonation_mfa_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_6a9788_idx'),
        ),
        migrations.RunPython(link_attempts_to_users, migrations.RunPython.noop),
    ]
