"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from .aws_secrets import load_aws_secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
# Production/staging: pull secrets from AWS Secrets Manager when
# AWS_SECRETS_MANAGER_SECRET_ID is set. No-op for local development.
load_aws_secrets()


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None or value.strip() == "":
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name):
    return [
        item.strip() for item in os.environ.get(name, "").split(",") if item.strip()
    ]


# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Secure by default: DEBUG is off unless DJANGO_DEBUG=true (set it in your local
# backend/.env). Never enable it on a deployed server.
DEBUG = env_bool("DJANGO_DEBUG", default=False)

# `manage.py test` talks to the app over plain HTTP, so HTTPS-only hardening is
# skipped there. A deployed server is never started through the test command.
TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

# The signing key must come from the environment or Secrets Manager. Only local
# development (DEBUG) may fall back to a throwaway key.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG or TESTING:
        SECRET_KEY = "django-insecure-local-development-only-key"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is required when DJANGO_DEBUG is not true. For local "
            "development add DJANGO_DEBUG=true to backend/.env."
        )

# Comma-separated host names, e.g. "api.example.com,localhost". In DEBUG an empty
# list allows localhost, matching Django's default behaviour.
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "accounts",
    "about_page",
    "drivers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.SessionTimeoutMiddleware",
    "accounts.middleware.AdminImpersonationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite").lower()

if DB_ENGINE == "mysql":
    required_database_variables = ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST")
    missing_database_variables = [
        variable
        for variable in required_database_variables
        if not os.environ.get(variable)
    ]

    if missing_database_variables:
        missing = ", ".join(missing_database_variables)
        raise ImproperlyConfigured(
            f"Missing required MySQL environment variables: {missing}"
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ["DB_HOST"],
            "PORT": os.environ.get("DB_PORT", "3306"),
            "CONN_MAX_AGE": 60,
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
elif DB_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    raise ImproperlyConfigured("DB_ENGINE must be either 'sqlite' or 'mysql'.")


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves the collected static files (Django admin assets) from the
# application process, so a bare Gunicorn deployment needs no separate web server.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Uploaded files use local storage during development. Production can swap the
# Django storage backend without changing the profile API.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Email (env-configurable; console backend by default so dev/CI need no config).
# An empty EMAIL_BACKEND (e.g. `EMAIL_BACKEND=` in .env) falls back to the
# console backend rather than an unusable empty backend string.
# See SPRINT_MFA_README_FINAL.md Section 4.1.
EMAIL_BACKEND = (
    os.environ.get("EMAIL_BACKEND") or "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@gooddriver.example")

# TOTP secret encryption key. Required with no default so any environment that
# starts the app is forced to provide one (fail loud at deploy time, not at
# first TOTP setup). Generate with:
# python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# See SPRINT_MFA_README_FINAL.md Section 4.5.
TOTP_ENCRYPTION_KEY = os.environ["TOTP_ENCRYPTION_KEY"]

# Logging: route app-level INFO logs (e.g. the SMS console fallback in
# accounts/services/sms.py) to the terminal so dev/CI can read sent codes.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Where the React app is served. Used to build links in emails (password reset).
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000").rstrip("/")

# Password reset links expire after this many seconds (default: 1 hour) and are
# single-use because the token is derived from the current password hash.
PASSWORD_RESET_TIMEOUT = int(os.environ.get("PASSWORD_RESET_TIMEOUT_SECONDS", 3600))
# Minimum seconds between reset emails to the same address.
PASSWORD_RESET_REQUEST_COOLDOWN = int(
    os.environ.get("PASSWORD_RESET_REQUEST_COOLDOWN_SECONDS", 60)
)

# "Is this your device?" check after sign-in. A browser the user marks as theirs
# is remembered this many days; sign-ins from other browsers, or after this many
# failed attempts within the window, ask the question again.
TRUSTED_DEVICE_DAYS = 90
TRUSTED_DEVICE_COOKIE_NAME = "gd_device"
SUSPICIOUS_FAILURE_THRESHOLD = 3
SUSPICIOUS_FAILURE_WINDOW_MINUTES = 15

# Server-enforced session limits, in seconds (accounts.middleware.
# SessionTimeoutMiddleware). "idle" signs the user out after that long without a
# request; "absolute" caps a session's total length however active it is. Admins
# hold privileged access, and shared-device sessions (the user answered "No" to
# the device question) may be left open for the next person. Other sessions keep
# Django's default lifetime.
SESSION_TIMEOUTS = {
    "admin": {"idle": 15 * 60, "absolute": 8 * 60 * 60},
    "shared_device": {"idle": 15 * 60, "absolute": None},
}

# Cross-origin access for the React app. In development the React dev server
# (http://localhost:3000) calls Django (http://localhost:8000). Deployed
# environments list their real origins, comma-separated, e.g.
# DJANGO_CORS_ALLOWED_ORIGINS=https://app.example.com
# /api/csrf/ issues the CSRF cookie; every non-GET request sends X-CSRFToken.
_DEV_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
CORS_ALLOWED_ORIGINS = env_list("DJANGO_CORS_ALLOWED_ORIGINS") or (
    _DEV_ORIGINS if DEBUG else []
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS") or (
    _DEV_ORIGINS if DEBUG else []
)

# The SPA reads the csrftoken cookie with JavaScript. If the API and the app are on
# different subdomains, set DJANGO_COOKIE_DOMAIN to the shared parent (".example.com")
# so both can see the cookies. Leave unset when both are served from one origin.
_COOKIE_DOMAIN = os.environ.get("DJANGO_COOKIE_DOMAIN") or None
SESSION_COOKIE_DOMAIN = _COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = _COOKIE_DOMAIN
SESSION_COOKIE_SAMESITE = os.environ.get("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE

# HTTPS hardening for deployed environments (everything below is off in DEBUG so
# local http://localhost keeps working).
if not (DEBUG or TESTING):
    SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    # Load balancers and health checks reach the app over plain HTTP.
    SECURE_REDIRECT_EXEMPT = [r"^api/health/$"]
    # Start small: browsers cache HSTS, so raise this only once HTTPS is proven.
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", 3600))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
    )
    SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # includeSubDomains and preload are deliberate opt-ins (they affect every
    # subdomain and are hard to undo), so their advisory checks are silenced.
    SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]
    # Set when a proxy/load balancer terminates TLS and forwards X-Forwarded-Proto.
    if env_bool("DJANGO_BEHIND_PROXY"):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}
