# Generated by Django 6.1.1 on 2026-10-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountprofile'),
        ('drivers', '0006_pointtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('rejected', 'Rejected application'), ('dropped', 'Dropped from sponsor')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='drivers.driver')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_status_changes', to='accounts.sponsorcompany')),
            ],
            options={
                'ordering': ('-changed_at', '-id'),
            },
        ),
    ]
